### ISSUE TITLE
Message window sometimes fails to output messages and/or outputs them in the wrong order

### ISSUE THREAD

**Issue by buddyp450** [evanyeung/terminal-slack#13]
For instance I could type

hello
world
hello

and it output that way to slack on the web UI but show up in terminal like

world
hello
hello

**Comment by evanyeung** [comment]
I think I figured out what you mean and why this is happening. If you were partially scrolled up in the message window and sent a message, the message would be appended to the bottom of the window, rather than the bottom of the chat. It showed up properly if the chat was reloaded.

I added a hack in 7eae1038f50f18cef526fb9a84860ab7b5d24509 to scroll to the bottom of the window whenever a new message is sent or received. I'm closing this for now. Further debugging will be required if you still have this issue.
